type Survey {
  testCases: [TestCase!] @relation
  viewport: Viewport!
  dummyTest: DummyTest!
  totalTime: Float!
  userAgent: String
  fingerprint: String
}

type Viewport {
  width: Int!
  height: Int!
  survey: Survey!
}

type DummyTest {
  nClusters: Int!
  nPoints: Int!
  viz: String!
  time: Float!
  answer: Int!
  survey: Survey!
}

type TestCase {
  order: Int!
  nClusters: Int!
  nPoints: Int!
  viz: String!
  overlap: Float!
  time: Float!
  answer: Int!
  survey: Survey!
}

type Query {
  allSurveys: [Survey!]
  allTestCases: [TestCase!]
}
